config/routes.rb
Rails.application.routes.draw do
  
  root 'owners#index'
  # root 'tops#index'

  resources :owners do
    collection do
      get :download
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/show'

  resources :plan_pins, only: [:create,:destroy] do
    collection do
      post :create_in_planform
    end
    member do
      delete :destroy_in_planform
    end
  end

  # ドラッグアンドドロップによるプランピン並び替えの登録用
  patch 'plan/:id/sort', to: 'plans#sort'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
  # devise_for :users

  # ユーザープロフィール画面は独自に作成する
  resources :users, only: [:show,:edit,:update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/owner.rb
class Owner < ApplicationRecord

  scope :search_by_name_partial, lambda {|name|where("name like ?", "%#{name}%")}
  scope :search_by_name_kana_forward, lambda {|name_kana|where("name_kana like ?", "#{name_kana}%")}

  scope :search_by_property_name_partial, lambda {|property_name|where("property_name like ?", "%#{property_name}%")}
  scope :search_by_property_name_kana_forward, lambda {|property_name_kana|where("property_name_kana like ?", "#{property_name_kana}%")}

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  require 'csv'
  before_action :authenticate_user!

  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index

    if params[:conditions].blank?
      @owners = Owner.all.order(:id)
    else
      @owners = Owner.search_by_name_partial(params[:conditions][:name]).
                      search_by_name_kana_forward(params[:conditions][:name_kana]).
                      search_by_property_name_partial(params[:conditions][:property_name]).
                      search_by_property_name_kana_forward(params[:conditions][:property_name_kana]).
                      order(:id)
    end

    respond_to do |format|
      format.html { render :index }
      format.js { render :index }
    end

  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to new_owner_path, notice: 'オーナー情報の作成に成功しました。' }
        # format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        # format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        # format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to edit_owner_path, notice: 'Owner was successfully updated.' }
        # format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        # format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        # format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # 在庫情報ダウンロードボタン押下時に呼び出される
  def download
    @owners = Owner.all


    header = ['オーナー名称', '（カナ）', '〒', '住所']
    generated_csv = CSV.generate(row_sep: "\r\n") do |csv|
      csv << header
      @owners.each do |owner|
        csv << [owner.name, owner.name_kana, owner.post_code, owner.address]
      end
    end

    send_data generated_csv.encode(Encoding::CP932, invalid: :replace, undef: :replace),
      filename: 'owner.csv',
      type: 'text/csv; charset=shift_jis'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :name_kana, :post_code, :address, :tel, :tel2, :fax, :property_name, :property_name_kana, :property_post_code, :property_address, :property_type, :bank, :branch, :account_type, :account_num, :account_name, :memo)
    end
end

app/helpers/owners_helper.rb
module OwnersHelper

  def get_account_type_name(type)

    case type
    when 0
      return "普通預金"
    when 1
      return "当座預金"
    else
      return "想定外データ"
    end
  end
end

app/views/owners/_form.html.erb
<!-- メッセージとか -->
<p id="notice_msg"><%= render 'layouts/show_notice_msg' %></p>
<p id="danger_msg"><%= render 'layouts/show_danger_msg' %></p>

<%= form_with(model: owner, local: true) do |form| %>

  <div class="field">
    <%= form.label "オーナー名" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "(カナ_全角入力)" %>
    <%= form.text_field :name_kana %>
  </div>

  <%= form.label "オーナーの住所" %>
  <div class="field">
    <%= form.label "〒" %>
    <%= form.text_field :post_code %>
  </div>

  <div class="field">
    <%= form.label "住所" %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label "電話①" %>
    <%= form.text_field :tel %>
  </div>

  <div class="field">
    <%= form.label "電話②" %>
    <%= form.text_field :tel2 %>
  </div>

  <div class="field">
    <%= form.label "FAX" %>
    <%= form.text_field :fax %>
  </div>

  <div class="field">
    <%= form.label "物件名" %>
    <%= form.text_field :property_name %>
  </div>

  <div class="field">
    <%= form.label "(カナ_全角入力)" %>
    <%= form.text_field :property_name_kana %>
  </div>

  <%= form.label "部件の住所" %>
  <div class="field">
    <%= form.label "〒" %>
    <%= form.text_field :property_post_code %>
  </div>

  <div class="field">
    <%= form.label "住所" %>
    <%= form.text_field :property_address %>
  </div>

  <div class="field">
    <%= form.label "物件の種類" %>
    <%= form.text_field :property_type %>
  </div>

  <%= form.label "銀行情報" %>
  <div class="field">
    <%= form.label "銀行名" %>
    <%= form.text_field :bank %>
      <%= form.label "……「銀行」まで入力" %>
  </div>

  <div class="field">
    <%= form.label "支店名" %>
    <%= form.text_field :branch %>
    <%= form.label "……「支店」は入力不要" %>
  </div>

  <div class="field">
    <%= form.label "口座種別" %>

    <%= form.radio_button :account_type, 0  %><%= "普通預金　　　　" %>
    <%= form.radio_button :account_type, 1  %><%= "当座預金" %>
  </div>

  <div class="field">
    <%= form.label "口座番号" %>
    <%= form.text_field :account_num %>
  </div>

  <div class="field">
    <%= form.label "口座名義" %>
    <%= form.text_field :account_name %>
  </div>

  <div class="field">
    <%= form.label "備考" %>
    <%= form.text_area :memo %>
  </div>

  <div class="actions">
    <%= form.submit "登録"%>
  </div>
<% end %>

app/views/owners/_index_table.html.erb
<table>
  <thead>
    <tr>
      <th class = "middle_cell">オーナー名</th>
      <th class = "middle_cell">（カナ）</th>
      <th class = "small_cell">〒</th>
      <th class = "wide_cell">住所（オーナー）</th>
      <th class = "middle_cell">電話①</th>
      <th class = "middle_cell">電話②</th>
      <th class = "middle_cell">Fax</th>
      <th class = "middle_cell">物件名</th>
      <th class = "middle_cell">（カナ）</th>
      <th class = "small_cell">〒</th>
      <th class = "wide_cell">住所（物件）</th>
      <th class = "middle_cell">物件種別</th>
      <th class = "middle_cell">銀行名</th>
      <th class = "middle_cell">支店名</th>
      <th class = "small_cell">普通/当座</th>
      <th class = "middle_cell">口座番号</th>
      <th class = "middle_cell">口座名義</th>
      <th class = "wide_cell">その他・備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.name_kana %></td>
        <td><%= owner.post_code %></td>
        <td><%= owner.address %></td>
        <td><%= owner.tel %></td>
        <td><%= owner.tel2 %></td>
        <td><%= owner.fax %></td>
        <td><%= owner.property_name %></td>
        <td><%= owner.property_name_kana %></td>
        <td><%= owner.property_post_code %></td>
        <td><%= owner.property_address %></td>
        <td><%= owner.property_type %></td>
        <td><%= owner.bank %></td>
        <td><%= owner.branch %></td>
        <td><%= get_account_type_name(owner.account_type) %></td>
        <td><%= owner.account_num %></td>
        <td><%= owner.account_name %></td>
        <td><%= owner.memo %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/owners/edit.html.erb
<h1>オーナー情報更新</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<!-- メッセージとか -->
<p id="notice_msg"><%= render 'layouts/show_notice_msg' %></p>
<p id="danger_msg"><%= render 'layouts/show_danger_msg' %></p>

<h1>オーナー一覧</h1>

<%= form_with scope: :conditions, url:owners_path,method: :get ,remote: true do |form| %>

  <div class="index_search_line">
    <div class="index_search_item">
      <%= form.label "オーナー名（部分一致）",class: "search_content_1" %>
      <%= form.text_field :name ,class: "search_content_2" %>

    </div>
    <div class="index_search_item">
      <%= form.label "オーナー名カナ（前方一致、全角で入力）",class: "search_content_1" %>
      <%= form.text_field :name_kana ,class: "search_content_2" %>
    </div>
  </div>

  <div class="index_search_line">
    <div class="index_search_item">
      <%= form.label "物件名（部分一致）",class: "search_content_1" %>
      <%= form.text_field :property_name ,class: "search_content_2" %>

    </div>
    <div class="index_search_item">
      <%= form.label "物件名カナ（前方一致、全角で入力）",class: "search_content_1" %>
      <%= form.text_field :property_name_kana ,class: "search_content_2" %>
    </div>
  </div>

  <div class="index_search_line">

    <div class="index_search_item">
      <%= form.submit "検索" ,id: "btn_search" , class: 'btn btn-primary btn_line_2' %>
      <!-- <a class='btn btn-primary btn_line_1'>クリア</a>……後回し -->
    </div>
    <div class="index_search_item">
    </div>
  </div>

<% end %>

<div class="index_search_item">
  <%= link_to '新規オーナー作成', new_owner_path  , class: 'btn btn-info btn_line_2' %>
  <%= link_to '全件ダウンロード', download_owners_path , class: 'btn btn-info btn_line_2'  %>
</div>

<div class = "index_table" id = "index_table" >

  <%= render 'index_table', owners: @owners %>

</div>


<br>

app/views/owners/index.js.erb
$("#index_table").html("<%= j(render 'owners/index_table', { owners: @owners }) %>")

app/views/owners/new.html.erb
<h1>新規オーナー作成</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Name kana:</strong>
  <%= @owner.name_kana %>
</p>

<p>
  <strong>Post code:</strong>
  <%= @owner.post_code %>
</p>

<p>
  <strong>Address:</strong>
  <%= @owner.address %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @owner.tel %>
</p>

<p>
  <strong>Tel2:</strong>
  <%= @owner.tel2 %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @owner.fax %>
</p>

<p>
  <strong>Property name:</strong>
  <%= @owner.property_name %>
</p>

<p>
  <strong>Property name kana:</strong>
  <%= @owner.property_name_kana %>
</p>

<p>
  <strong>Property post code:</strong>
  <%= @owner.property_post_code %>
</p>

<p>
  <strong>Property address:</strong>
  <%= @owner.property_address %>
</p>

<p>
  <strong>Property type:</strong>
  <%= @owner.property_type %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @owner.bank %>
</p>

<p>
  <strong>Branch:</strong>
  <%= @owner.branch %>
</p>

<p>
  <strong>Account type:</strong>
  <%= @owner.account_type %>
</p>

<p>
  <strong>Account num:</strong>
  <%= @owner.account_num %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @owner.account_name %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @owner.memo %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>